# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/aaue_db
spring.datasource.username=postgres
spring.datasource.password=1096
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2

server.port=8081
server.address=0.0.0.0